spring:
  datasource:
    url: jdbc:postgresql://database-1-backvotos.cgfbqvadtdmx.us-east-1.rds.amazonaws.com:5432/banco_desafio_back_votos
    driverClassName: org.postgresql.Driver
    username: postgresroot123
    password: EGGI6YbbUNN7LiHWxHPr
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  api-docs:
    path: /v3/back-votos-docs
  swagger-ui:
    operationsSorter: method

aws:
  credentials:
    access-key: AKIAZUQB7BEBG27VRJ4M
    secret-key: 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
  queue:
    name: fila-assembleias-finalizadas.fifo
