spring:
  datasource:
    url: jdbc:h2:file:./test6
    driverClassName: org.h2.Driver
    username: sa
    password: 1234
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
springdoc:
  api-docs:
    path: /v3/back-votos-docs
  swagger-ui:
    operationsSorter: method